<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>getSupplierName</name>
  <uuid>f2787653-d1cf-4479-9752-87441eb62014</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the generated text of 'ML model invocation' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
