<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>getSupplierName</name>
  <uuid>e4a789e5-7dc2-4137-9101-41945ad0621f</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the generated token count of 'ML model invocation' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
