<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>getSupplierName</name>
  <uuid>f5e6c64a-76ee-4ea3-911b-c850a928ad1b</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new ML model input where
		the recommendation is recommendation ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
