<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>overorder_Email_Draft</name>
  <uuid>7acf08cf-7aa4-45b4-a7f7-4f239ec705de</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'ML model invocation' is in error
then
	set decision to the message of the error of 'ML model invocation' ;
else
	set decision to null ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
