<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>overorder_Email_Draft</name>
  <uuid>261d5ac3-152a-4964-bf99-f772ef996d8b</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the generated token count of 'ML model invocation' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
