<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>overorder_Email_Draft</name>
  <uuid>f47f614e-88b7-4a5d-8a47-1d31f34f4120</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the generated token count of 'ML model invocation' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
