<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>overorder_Email_Draft</name>
  <uuid>b650672e-4563-4330-90b2-8a0c53b826f8</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the input token count of 'ML model invocation' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
