<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>noMinOrderNotification</name>
  <uuid>2868ed3e-6f56-4eff-9415-50c22eeb3cbe</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the generated text of 'ML model invocation' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
