<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>noMinOrderNotification</name>
  <uuid>b9d8acef-161c-4125-b6ad-23aa80c426a7</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the stop reason of 'ML model invocation' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
