<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>noMinOrderNotification</name>
  <uuid>6090a9db-d3d0-4a01-b433-2aa135d9ccf5</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new ML model input where
		the order qty is order_qty ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
