<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>rule</name>
  <uuid>be24663b-93fd-4c56-a094-ea418446e588</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the last element in the predictions ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
