<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>overorder_Email_Draft</name>
  <uuid>87f3e4d7-c270-419a-a01f-01b4d9bd9ec7</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'ML model invocation' is in error
then
	set decision to the code of the error of 'ML model invocation' ;
else
	set decision to null ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
