<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>overorder_Email_Draft</name>
  <uuid>f3842817-3d8b-4ae6-810d-292e93a3975a</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the generated text of 'ML model invocation' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
