<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>noMinOrderNotification</name>
  <uuid>72df5a47-d18e-4571-90bc-12d37eac7261</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'ML model invocation' is in error
then
	set decision to the code of the error of 'ML model invocation' ;
else
	set decision to null ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
