<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>noMinOrderNotification</name>
  <uuid>0660d742-0eb2-461f-b81d-0840eb83bd16</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the input token count of 'ML model invocation' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
