<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>rule 01</name>
  <uuid>fe5bf43f-4824-460d-ae88-84491029465c</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new prediction where
		the predictions are the predictions;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
