<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>rule</name>
  <uuid>8fdbc672-b8b3-4dcc-950a-224f3a6525b2</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to <a string> ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
