<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>getSupplierName</name>
  <uuid>068f3046-2b89-4426-9024-e43d705fffc3</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the stop reason of 'ML model invocation' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
