<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>overorder_Email_Draft</name>
  <uuid>b1f377a0-78c5-4c8d-b55c-91a66cbb2dc5</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new ML model input where
		the reorder qty is reorder_qty , 
		the value is value , 
		the supplier is supplier ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
