<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>orderMet</name>
  <uuid>289d0bae-91c9-42d3-b315-7745d9dc28ab</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the generated token count of 'ML model invocation' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
