<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>orderMet</name>
  <uuid>0d7a3e87-3ad3-49ef-8cd6-42b1d2d5fac7</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the generated text of 'ML model invocation' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
