<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>orderMet</name>
  <uuid>745c0f79-0958-45f5-a3a9-9ebacf840ee5</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the stop reason of 'ML model invocation' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
