<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>orderMet</name>
  <uuid>27d749ce-d426-452a-a3bb-ccf6145700e3</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the input token count of 'ML model invocation' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
