<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>getSupplierName</name>
  <uuid>f2d6d906-448f-46fc-9d20-05ce1167df11</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new ML model input where
		the recommendation is recommendation ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
